spring.application.name=BtgFondosMS
server.port=8080
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.defaults.enabled=false
management.health.diskspace.enabled=true

spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT
jwt.secret=btg-fondos-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000