spring.application.name=BtgFondosMS

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=BTG
spring.data.mongodb.username=btg
spring.data.mongodb.password=btg123
spring.data.mongodb.authentication-database=BTG